services:
  postgres:
    image: 'ankane/pgvector:v0.5.0'
    restart: always
    environment:
      - 'POSTGRES_DB=vector_store'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGPASSWORD=postgres'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d vector_store"]
      interval: 2s
      timeout: 20s
      retries: 10
  pgadmin:
    container_name: pgadmin-container
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pdadmin@pgadmin.com}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}'
    volumes:
      - './servers.json:/pgadmin4/servers.json'
    ports:
      - '${PGADMIN_PORT:-5050}:80'